### ISSUE TITLE
Working with Simulation 

### ISSUE THREAD

**Issue by ArghyaChatterjee** [leggedrobotics/art_planner#1]
Hi, thanks for open sourcing your work. I can reproduce this package [cerberus_anymal_locomotion](https://github.com/leggedrobotics/cerberus_anymal_locomotion). Is there any walk through tutorial on how to integrate this package with ANYmal B/C ??

**Comment by lorenwel** [comment]
Hi, 

thanks for your interest in my work. Unfortunately, there is no readily available way to interface this planner with the package you mentioned. That just includes the basic locomotion stack for ANYmal, but the `art_planner` relies on mapping and localization to provide an elevation map and the robot pose. 
If you have some form of localization running in your sim, you could try running [elevation_mapping](https://github.com/ANYbotics/elevation_mapping) to provide an elevation map.
