### ISSUE TITLE
error with goal set

### ISSUE THREAD

**Issue by xin111222** [leggedrobotics/art_planner#10]
When I set 2D Nav Goal in rviz,some problems appear .
[ WARN] [1684226863.598702089]: Invalid argument passed to lookupTransform argument target_frame in tf2 frame_ids cannot be empty
[ERROR] [1684226863.598769350]: Could not transform goal pose to map frame. Not planning.

**Comment by nanbwrn** [comment]
hi,@xin111222 
have you resolved this issue? I'm facing the same problem. I really appreciate your help.
