### ISSUE TITLE
Issues with TFs

### ISSUE THREAD

**Issue by umsarmy** [leggedrobotics/art_planner#16]
Hello

I am getting some issues with TFs and lookup transforms which I am not able to debug.

After launching the art_planner and publishing a goal on `/art_planner/plan_to_goal/goal ` topic, I am getting the following error.

`[ WARN] [1705064013.881655509]: Invalid argument passed to lookupTransform argument source_frame in tf2 frame_ids cannot be empty
[ERROR] [1705064013.881744310]: Could not transform goal pose to map frame. Not planning.
`

Please help me resolve this issue. Thanks.

**Comment by nanbwrn** [comment]
Hi, have you resolved this issue? I'm facing the same problem. I really appreciate your help.

**Comment by nanbwrn** [comment]
hi,@umsarmy 
have you resolved this issue? I'm facing the same problem. I really appreciate your help.

**Comment by G7-3208** [comment]
have you resolved this issue? I'm facing the same problem.
