### ISSUE TITLE
error: no matching function for call to ‘Eigen::Map

### ISSUE THREAD

**Issue by zltnl** [leggedrobotics/art_planner#2]
Hi, thanks for open sourcing your work.
![image](https://user-images.githubusercontent.com/45987911/146499554-93d04def-aa8b-434d-b935-64160565f107.png)

**Comment by lorenwel** [comment]
Hi, 

could you please provide a bit more detail how you were trying to build the package and what your system specs are?
I have tested this package under Ubuntu 20.04 with ROS Noetic. 
According to your console output you are still using ROS Melodic (possibly on 18.04 ?) which might use an older, imcompatible Eigen version.

**Comment by zltnl** [comment]
你好，邮件已经收到，尽快给你回复。

**Comment by lorenwel** [comment]
Closing this for now. Please reopen if this issue persists.
