### ISSUE TITLE
Difference with GB Planner/MB Planner/GB Planner2

### ISSUE THREAD

**Issue by ArghyaChatterjee** [leggedrobotics/art_planner#3]
Hi, Sorry for my ignorance but can you tell me what's the difference between this 'art planner' package and [gb planner](https://github.com/ntnu-arl/gbplanner_ros) and [mb planner](https://github.com/ntnu-arl/mbplanner_ros) package ??

**Comment by lorenwel** [comment]
Hi. The planners you linked are global exploration planners which work for both ground robots and drones (but were originally conceived for drones). 
This work is a local navigation planner specifically for legged robots.
