### ISSUE TITLE
error with navigation_msgs

### ISSUE THREAD

**Issue by mengchongxi** [leggedrobotics/art_planner#7]
thanks for your shared works, when i compile with it, i meet a mistake like it

CMake Error at /opt/ros/noetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "navigation_msgs"
  with any of the following names:

    navigation_msgsConfig.cmake
    navigation_msgs-config.cmake

i can not find suitable navigation_msgs, thanks for your help

**Comment by lorenwel** [comment]
Thanks for the hint. Fixed with #8
